spring:
  datasource:
    url: jdbc:sqlserver://myclassroombackend.database.windows.net:1433;database=myClassroom;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: myClassroom@myclassroombackend
    password: educationPlatform12345
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2016Dialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days